# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PingPongService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PingPongService.proto\x12\x14\x63om.dubrouskaya.grpc\"\x1f\n\x0bPingRequest\x12\x10\n\x08pingWord\x18\x01 \x01(\t\" \n\x0cPongResponse\x12\x10\n\x08pongWord\x18\x01 \x01(\t2_\n\x0fPingPongService\x12L\n\x03say\x12!.com.dubrouskaya.grpc.PingRequest\x1a\".com.dubrouskaya.grpc.PongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PingPongService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=47
  _globals['_PINGREQUEST']._serialized_end=78
  _globals['_PONGRESPONSE']._serialized_start=80
  _globals['_PONGRESPONSE']._serialized_end=112
  _globals['_PINGPONGSERVICE']._serialized_start=114
  _globals['_PINGPONGSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
